name: Deploy con OIDC a EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del c칩digo
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS con OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1  # Cambi치 esto si tu instancia est치 en otra regi칩n

      - name: Deploy remoto a EC2
        run: |
          echo "游댏 Conectando a EC2 con Session Manager"
          INSTANCE_ID=$(aws ec2 describe-instances \
            --filters "Name=tag:Name,Values=SystemAlex" \
            --query "Reservations[].Instances[].InstanceId" \
            --output text)

          echo "游닍 Ejecutando comandos remotos"
          aws ssm send-command \
            --instance-ids "$INSTANCE_ID" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy desde GitHub Actions" \
            --parameters commands='
              cd /home/systemalex/WorkScheduleTracker &&
              git fetch --all &&
              git reset --hard origin/main &&
              npm prune &&
              npm install --omit=dev &&
              npm audit fix || true &&
              npm run build &&
              sudo systemctl restart scheduletracker.service
              sudo systemctl status scheduletracker.service --no-pager
            ' \
            --region us-east-1 \
            --output text
