name: Deploy to AWS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Ejecutar deploy remoto
        run: |
          ssh -tt -o StrictHostKeyChecking=no systemalex@systemalex.cbu.net << 'EOF'
            cd /home/systemalex/WorkScheduleTracker
            git fetch --all
            git reset --hard origin/main
            npm prune
            npm install --omit=dev
            npm audit fix
            npm run build
            sudo systemctl restart scheduletracker.service
          EOF
