name: Deploy con OIDC a EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS con OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Deploy remoto a EC2 usando pnpm
        run: |
          echo "🔐 Conectando a EC2 con Session Manager"
          INSTANCE_ID=$(aws ec2 describe-instances \
            --filters "Name=tag:Name,Values=SystemAlex" \
            --query "Reservations[].Instances[].InstanceId" \
            --output text)

          echo "📦 Ejecutando comandos remotos"
          aws ssm send-command \
            --instance-ids "$INSTANCE_ID" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy desde GitHub Actions con pnpm" \
            --parameters commands='
                export HOME=/home/systemalex &&
                git config --global --add safe.directory /home/systemalex/WorkScheduleTracker &&
                cd /home/systemalex/WorkScheduleTracker &&
                git fetch --all &&
                git reset --hard origin/main &&
                curl -fsSL https://get.pnpm.io/install.sh | bash &&
                export PATH="$HOME/.local/share/pnpm:$PATH" &&
                pnpm install &&
                pnpm run build &&
                sudo systemctl restart scheduletracker.service &&
                sudo systemctl status scheduletracker.service --no-pager
            ' \
            --region us-east-1 \
            --output text
